"""Initial migration

Revision ID: 61290a444871
Revises: 
Create Date: 2026-02-11 09:52:54.339896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61290a444871'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('file_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_access_logs_id'), 'file_access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_file_access_logs_timestamp'), 'file_access_logs', ['timestamp'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('azure_devops_pat_encrypted', sa.Text(), nullable=False),
    sa.Column('anthropic_api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('azure_devops_org_url', sa.String(length=500), nullable=False),
    sa.Column('azure_devops_project', sa.String(length=255), nullable=False),
    sa.Column('claude_model', sa.String(length=100), nullable=False),
    sa.Column('work_folder_path', sa.String(length=1000), nullable=True),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_table('work_item_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('work_item_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_item_history_created_at'), 'work_item_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_item_history_id'), 'work_item_history', ['id'], unique=False)
    op.create_index(op.f('ix_work_item_history_work_item_id'), 'work_item_history', ['work_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_item_history_work_item_id'), table_name='work_item_history')
    op.drop_index(op.f('ix_work_item_history_id'), table_name='work_item_history')
    op.drop_index(op.f('ix_work_item_history_created_at'), table_name='work_item_history')
    op.drop_table('work_item_history')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_file_access_logs_timestamp'), table_name='file_access_logs')
    op.drop_index(op.f('ix_file_access_logs_id'), table_name='file_access_logs')
    op.drop_table('file_access_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
